import type { FighterConfig } from "./types";

const baseAttacks = {
  light: { damage: 7, range: 88, knockback: 260, cooldown: 340, windup: 70, active: 120 },
  heavy: { damage: 13, range: 104, knockback: 430, cooldown: 720, windup: 130, active: 150 },
  special: { damage: 16, range: 138, knockback: 540, cooldown: 1550, windup: 170, active: 180 },
};

export const fighters: FighterConfig[] = [
  {
    id: "proposal-rock",
    displayName: "Proposal Rock",
    title: "Stonehearted Guardian",
    role: "Bruiser / Anchor",
    rarity: "Legendary",
    bio: "A landmark fighter built for holding ground, absorbing pressure, and ending close-range trades with huge knockback.",
    strengths: ["Massive burst damage", "High effective durability", "Dominates short lanes"],
    weaknesses: ["Slow recovery windows", "Lower mobility", "Needs commitment"],
    passiveName: "Basalt Poise",
    passiveDescription: "Takes reduced incoming damage and stays threatening even while shield pressure is high.",
    spriteKey: "fighter-proposal-rock",
    maxHealth: 118,
    maxShield: 78,
    shieldRechargePerSecond: 18,
    speed: 230,
    jumpPower: 670,
    defense: 0.82,
    tint: 0xffffff,
    specialName: "Proposal Spin Charge",
    aiProfile: "defensive",
    attacks: {
      light: { ...baseAttacks.heavy, damage: 15, range: 92, knockback: 560, cooldown: 820, windup: 70, active: 120 },
      heavy: { ...baseAttacks.special, damage: 25, range: 210, knockback: 760, cooldown: 2100, windup: 260, active: 260 },
      special: { ...baseAttacks.special, damage: 31, range: 126, knockback: 900, cooldown: 2400, windup: 0, active: 560 },
    },
  },
  {
    id: "chelan",
    displayName: "The Chelan",
    title: "Arcade Current",
    role: "Skirmisher / Zoner",
    rarity: "Rare",
    bio: "A fast, flexible beach fighter who controls space with quick taps, flying beach toys, and a cinematic finishing special.",
    strengths: ["Fast repositioning", "Quick shield recharge", "Explosive special finisher"],
    weaknesses: ["Lower shield pool", "Moderate defense", "Needs spacing discipline"],
    passiveName: "Brightwater Tempo",
    passiveDescription: "Recovers shield quickly, letting patient players reset between quick exchanges.",
    spriteKey: "fighter-chelan",
    maxHealth: 108,
    maxShield: 54,
    shieldRechargePerSecond: 24,
    speed: 270,
    jumpPower: 650,
    defense: 0.92,
    tint: 0xffffff,
    specialName: "Chelanmania Driver",
    aiProfile: "steady",
    attacks: {
      light: { ...baseAttacks.light },
      heavy: { ...baseAttacks.special, damage: 13, range: 520, knockback: 430, cooldown: 860, windup: 80, active: 520 },
      special: { ...baseAttacks.special, damage: 28, range: 156, knockback: 820, cooldown: 2600, windup: 90, active: 250 },
    },
  },
  {
    id: "ocean",
    displayName: "The Ocean",
    title: "Endless Tide",
    role: "Boss / Zone Control",
    rarity: "Boss",
    bio: "A relentless arena force with no shield, enormous health, and wide attacks that punish players who drift into the tide.",
    strengths: ["Huge health pool", "Wide threat ranges", "Constant pressure"],
    weaknesses: ["No shield", "No ground speed", "Predictable positioning"],
    passiveName: "Undertow",
    passiveDescription: "Trades shield for raw health and oppressive reach, forcing opponents to manage distance carefully.",
    spriteKey: "fighter-ocean",
    maxHealth: 155,
    maxShield: 0,
    shieldRechargePerSecond: 0,
    speed: 0,
    jumpPower: 700,
    defense: 0.78,
    tint: 0xffffff,
    specialName: "Sneaker Wave",
    aiProfile: "zoning",
    attacks: {
      light: { ...baseAttacks.light, range: 120 },
      heavy: { ...baseAttacks.heavy, range: 150 },
      special: { ...baseAttacks.special, range: 190, cooldown: 1250 },
    },
  },
  {
    id: "rip-rap",
    displayName: "Rip Rap",
    title: "Jagged Breakwater",
    role: "Counter / Defender",
    rarity: "Epic",
    bio: "A technical defender who wins by stuffing approaches, punishing overextensions, and turning small openings into hard knockback.",
    strengths: ["Strong counter hits", "Solid shield value", "Good defensive profile"],
    weaknesses: ["Shorter light range", "Lower recharge", "Requires timing"],
    passiveName: "Rough Edges",
    passiveDescription: "Rewards well-timed defensive play with heavier punish windows after opponents step too close.",
    spriteKey: "fighter-rip-rap",
    maxHealth: 112,
    maxShield: 70,
    shieldRechargePerSecond: 16,
    speed: 245,
    jumpPower: 620,
    defense: 0.86,
    tint: 0x6f766d,
    specialName: "Breakwater Boulder",
    aiProfile: "defensive",
    attacks: {
      light: { ...baseAttacks.light, damage: 9, range: 78 },
      heavy: { ...baseAttacks.heavy, damage: 15, range: 132, knockback: 560, cooldown: 900, windup: 180, active: 210 },
      special: { ...baseAttacks.special, damage: 18, range: 70, knockback: 680, cooldown: 1900, windup: 120, active: 4200 },
    },
  },
  {
    id: "the-house",
    displayName: "The House",
    title: "Porchside Brawler",
    role: "Aggressor / Balanced",
    rarity: "Epic",
    bio: "A confident pressure fighter with balanced tools, steady movement, and a special that keeps opponents pinned near the porch.",
    strengths: ["Balanced stat spread", "Reliable pressure", "Accessible attack timings"],
    weaknesses: ["No extreme stat peaks", "Can be out-ranged", "Needs initiative"],
    passiveName: "Home Advantage",
    passiveDescription: "Keeps a consistent tempo across trades, making it easier to maintain pressure after clean hits.",
    spriteKey: "fighter-the-house",
    maxHealth: 110,
    maxShield: 60,
    shieldRechargePerSecond: 21,
    speed: 260,
    jumpPower: 640,
    defense: 0.9,
    tint: 0xd1ba84,
    specialName: "Porch Swing",
    aiProfile: "aggressive",
    attacks: {
      light: { ...baseAttacks.light, damage: 8 },
      heavy: { ...baseAttacks.heavy, damage: 15 },
      special: { ...baseAttacks.special, damage: 18, range: 146, knockback: 590 },
    },
  },
  {
    id: "duck-flag",
    displayName: "Duck Flag",
    title: "Autzen Summoner",
    role: "Summoner / Ranged",
    rarity: "Legendary",
    bio: "A sideline spellcaster that calls Oregon football legends onto the beach, turning open field into passing lanes and rushing gaps.",
    strengths: ["Long-range arcing pressure", "Summoned allies control space", "High special uptime pressure"],
    weaknesses: ["Needs charge timing", "Lower defense", "Can be rushed during summons"],
    passiveName: "Sco Ducks",
    passiveDescription: "Summoned attacks gain value when Duck Flag creates enough space for them to travel.",
    spriteKey: "fighter-duck-flag",
    maxHealth: 104,
    maxShield: 58,
    shieldRechargePerSecond: 22,
    speed: 252,
    jumpPower: 642,
    defense: 0.94,
    tint: 0xffffff,
    specialName: "Mascot Moto Loop",
    aiProfile: "zoning",
    attacks: {
      light: { ...baseAttacks.light, damage: 11, range: 190, knockback: 420, cooldown: 780, windup: 80, active: 520 },
      heavy: { ...baseAttacks.heavy, damage: 12, range: 620, knockback: 520, cooldown: 1180, windup: 0, active: 1500 },
      special: { ...baseAttacks.special, damage: 8, range: 148, knockback: 310, cooldown: 5200, windup: 120, active: 10000 },
    },
  },
];

export function getFighter(id: string): FighterConfig {
  const fighter = fighters.find((candidate) => candidate.id === id);
  if (!fighter) {
    throw new Error(`Unknown fighter: ${id}`);
  }
  return fighter;
}
